---
- name: Set apache run user in envvars
  lineinfile: >
    line="export APACHE_RUN_USER={{ apache_run_user }}"
    regexp="^export APACHE_RUN_USER="
    state=present
    dest=/etc/apache2/envvars
  notify: restart apache

- name: Set apache run group in envvars
  lineinfile: >
    line="export APACHE_RUN_GROUP={{ apache_run_group }}"
    regexp="^export APACHE_RUN_GROUP="
    state=present
    dest=/etc/apache2/envvars
  notify: restart apache

- name: Set port in ports.conf
  lineinfile: >
    line="Listen *:{{ apache_listen_port }}"
    regexp="^Listen "
    state=present
    dest=/etc/apache2/ports.conf
  notify: restart apache

- name: Enable SSL SNI in ports.conf
  lineinfile: >
    line="NameVirtualHost *:443"
    regexp="^NameVirtualHost .*:443"
    state=present
    dest=/etc/apache2/ports.conf
  notify: restart apache
  when: apache_ssl_sni

- name: Create SSL directory
  file: path=/etc/apache2/ssl state=directory