# This is the main task, which simply includes all necessary sub tasks.
---
- include: install.yml
  tags: [apache, apache-install]

- include: configure.yml
  tags: [apache, apache-configure]

- include: modules.yml
  tags: [apache, apache-modules]

- include: virtualhosts.yml
  tags: [apache, apache-virtualhosts]

- include: directories.yml
  tags: [apache, apache-directories]

- name: Ensure Apache is started and set to run on startup.
  service: name=apache2 state=started enabled=yes