---
- name: Setup virtualhosts
  template: >
    src=vhost.conf.j2
    dest=/etc/apache2/sites-enabled/{{ item }}.conf
    owner=root
    group=root
    mode=0644
  with_items: apache_virtualhosts.keys()
  when: apache_virtualhosts|length > 0
  notify: restart apache

- name: Find enabled virtualhosts
  shell: ls -1 /etc/apache2/sites-enabled/
  register: vhosts_enabled
  changed_when: False

- name: Disable unmanaged virtualhosts
  file: name=/etc/apache2/sites-enabled/{{ item }} state=absent
  with_items: vhosts_enabled.stdout_lines
  when: item[:-5] not in apache_virtualhosts.keys()
  notify: restart apache