---
- name: Setup virtualhosts
  template: >
    src=vhost.conf.j2
    dest=/etc/apache2/sites-enabled/{{ item.value.priority|default(20) }}-{{ item.key }}.conf
    owner=root
    group=root
    mode=0644
  with_dict: apache_virtualhosts
  notify: restart apache

- name: Upload SSL cert files
  copy: src={{ item.value.ssl_certfile }} dest=/etc/apache2/ssl/{{ item.key }}.crt
  with_dict: apache_virtualhosts
  when: item.value.ssl_certfile is defined
  notify: restart apache

- name: Upload SSL key files
  copy: src={{ item.value.ssl_keyfile }} dest=/etc/apache2/ssl/{{ item.key }}.key
  with_dict: apache_virtualhosts
  when: item.value.ssl_keyfile is defined
  notify: restart apache

- name: Upload SSL chain files
  copy: src={{ item.value.ssl_chainfile }} dest=/etc/apache2/ssl/{{ item.key }}-chain.crt
  with_dict: apache_virtualhosts
  when: item.value.ssl_chainfile is defined
  notify: restart apache

- name: Upload SSL CA cert files
  copy: src={{ item.value.ssl_ca_certfile }} dest=/etc/apache2/ssl/{{ item.key }}-ca.crt
  with_dict: apache_virtualhosts
  when: item.value.ssl_ca_certfile is defined
  notify: restart apache

- name: Upload SSL CA Revocation files
  copy: src={{ item.value.ssl_ca_revocationfile }} dest=/etc/apache2/ssl/{{ item.key }}-ca.crl
  with_dict: apache_virtualhosts
  when: item.value.ssl_ca_revocationfile is defined
  notify: restart apache

- name: Find enabled virtualhosts
  shell: ls -1 /etc/apache2/sites-enabled/
  register: vhosts_enabled
  changed_when: False

- name: Remove unmanaged virtualhosts
  file: name=/etc/apache2/sites-enabled/{{ item }} state=absent
  with_items: vhosts_enabled.stdout_lines
  when: item[3:-5] not in apache_virtualhosts.keys()
  notify: restart apache